### ISSUE TITLE
Support KairosDB diff aggregator.

### ISSUE THREAD

**Issue by bergquist** [grafana/kairosdb-datasource#1]
It looks like Grafana doesn't support the KairosDB diff aggregator.

This is needed for things like network metrics since these just accumulate.

based on https://github.com/grafana/grafana/issues/2967

**Comment by zachm** [comment]
+1 I'd really like this too.

**Comment by farzadpanahi** [comment]
+1 I can't imagine why this would be missing

**Comment by jifwin** [comment]
+1

**Comment by jifwin** [comment]
Added "diff" aggregator a while ago.
