### ISSUE TITLE
Adding tags/group by/aggregators affects other queries in same graph

### ISSUE THREAD

**Issue by simonsdeng** [grafana/kairosdb-datasource#16]
When editing a graph with multiple KairosDB queries, the entry fields for adding tags, group by values, and aggregators are enabled for every query for that graph when I press the "+" button rather than just for that specific query. See attached image for example:

<img src="https://cloud.githubusercontent.com/assets/5785005/16350070/4b54c990-3a11-11e6-89d6-698d95013f7f.png" width="500" />

Looking at the plugin code it seems like this is caused by the fact that most of the Angular model is stored in `ctrl.panel` instead of `ctrl.target`, which would make these settings panel-specific rather than query-specific. Replacing all instances of `panel` with `target` in [`query_ctrl.js`](https://github.com/grafana/kairosdb-datasource/blob/master/query_ctrl.js) and [`partials/query.editor.html`](https://github.com/grafana/kairosdb-datasource/blob/master/partials/query.editor.html) seems to fix this issue.

**Comment by bergquist** [comment]
closed by https://github.com/grafana/kairosdb-datasource/pull/17
