### ISSUE TITLE
Templated dashboards for KairosDB don't work with variable tag names. 

### ISSUE THREAD

**Issue by bergquist** [grafana/kairosdb-datasource#2]
Tag names can't be templated it seems.

The following is supported:

hostname=$hostname

but if I do something like

$role = true

That won't work. In fact, as soon as I click the + button , the entire chart goes away, so does the line I just added, and the chart is blank.

I've duplicated this a number of times and I get the same problem every time.

I don't get anything logged in the JS console.

I've confirmed that the actual tags are there. If I use them manually they work. It's just that I can't make them templated.

from
https://github.com/grafana/grafana/issues/2966

**Comment by vguhesan** [comment]
I would like this feature.

**Comment by mahdianpeyman** [comment]
+1

**Comment by congshenV** [comment]
+1

**Comment by fooltux** [comment]
+1

**Comment by jifwin** [comment]
Implemented in v3.0.0
