### ISSUE TITLE
http settings not showing in gui

### ISSUE THREAD

**Issue by majorcorn** [grafana/kairosdb-datasource#32]
When I go to add data source, then select KairosDB I receive an error:

Plugin Error
Error: XHR error (404 Not Found)
loading
http://X.XXX.XXX.XXX:3000/public/app/plugins/datasource/grafana-kairosdb-datasource/module.js?
bust=1473961126481 Error loading http://X.XXX.XXX.XXX:3000/public/app/plugins/datasource/grafana-kairosdb-datasource/module.js

Any help would be greatly appreciated.  Thanks.

**Comment by jifwin** [comment]
Fixed.
