### ISSUE TITLE
templating option "Include All option" does not seem to be working

### ISSUE THREAD

**Issue by samuelbenhamou** [grafana/kairosdb-datasource#41]
when using templating with whatever query 
in my case : _**metrics(cpu.system.value_rate)**_
I get the correct values returned:

- cpu.0.cpu.system.value_rate
- cpu.1.cpu.system.value_rate
- cpu.2.cpu.system.value_rate
- cpu.3.cpu.system.value_rate

Selecting either separate value or even multiple if the selection options has been ticked works correctly but when I select all, I end up with an empty graph because from what I gathered the query sent pass on "$__all" as the name
is there any "**_Custom all value_**" to be used maybe or is it a bug ?

**Comment by samuelbenhamou** [comment]
found the culprit:
-          if (variable.current.value === "$__all") {
+          if (variable.current.value[0] === "$__all") {
in the datasource.js

**Comment by jifwin** [comment]
Thank you @samuelbenhamou . That was the reason indeed. Fixed.
