### ISSUE TITLE
groupby does not work

### ISSUE THREAD

**Issue by 0zeroth** [grafana/kairosdb-datasource#42]
It appears that when KairosDB has multiple values for a metric with the same timestamp, but different tags, Grafana just averages the values. This behaviour seems default - it happens when no tags / group by / aggregator is set, and the behaviour does not change even when "group by" is set.

The following query in the KairosDB web ui: 
```
{
  "metrics": [
    {
      "tags": {},
      "name": "metricB",
      "group_by": [
        {
          "name": "tag",
          "tags": [
            "index1"
          ]
        }
      ],
      "aggregators": [
        {
          "name": "sum",
          "align_sampling": true,
          "sampling": {
            "value": "1",
            "unit": "milliseconds"
          }
        }
      ]
    }
  ],
  "cache_time": 0,
  "start_relative": {
    "value": "4",
    "unit": "years"
  }
}
```
gives a graph like:
![image](https://cloud.githubusercontent.com/assets/8716660/22094526/1e5cdb30-de62-11e6-8f85-2402128ab020.png)

A similar config in Grafana does not work:

![image](https://cloud.githubusercontent.com/assets/8716660/22094545/4881d94c-de62-11e6-8ec9-92889498b282.png)

![image](https://cloud.githubusercontent.com/assets/8716660/22094673/2c3b0244-de63-11e6-95d8-0d65cb6814eb.png)

Note the Grafana data points are the average of the datapoints shown in the KairosDB web UI

**Comment by tmalaska** [comment]
I'm experiencing this as well

**Comment by jifwin** [comment]
I'm going to look at that soon.

**Comment by TedBear42** [comment]
Hey jifwin,

If you have time next week I would love to connect.  We are thinking about using this plugin for a very large project, and we would like to become more involved.  

Please send me an e-mail if you are free I would love to chat.

Ted Malaska

**Comment by jifwin** [comment]
Hi @TedBear42 
I'd love to talk, but I can't find any contact point to you, also github doesn't support private messaging anymore. Please send me an email: 
![text2image_p34941_20170130_164212](https://cloud.githubusercontent.com/assets/5750402/22431944/946ff1ea-e713-11e6-85ba-aaef926b941a.jpg)

**Comment by jifwin** [comment]
@0zeroth 
You should click on the little "plus" icon to apply grouping by. If that is not the case please reopen this issue.

Also please note that this UI looks so strange since it's not upgraded to Grafana 4 standards. Once we merge #40 it should be refined.
