### ISSUE TITLE
problem installing from source

### ISSUE THREAD

**Issue by rybit** [grafana/kairosdb-datasource#43]
Hi - I was using the 1.1.0 version linked to by grafana, but I wanted to more up to date features. So I am installing it from source. 

After following a slightly modified version of your instructions (below) I am getting this error when creating a new datasource. 
![image](https://cloud.githubusercontent.com/assets/406376/22353358/d91c2c4c-e3d4-11e6-81be-0822d8b74527.png)

instructions:

```
cd /var/lib/grafana/plugins
sudo git clone https://github.com/grafana/kairosdb-datasource.git
cd kairosdb-datasource
sudo npm install
sudo grunt
sudo service kairosdb restart
```

I can now see the datasource, but I don't see it working. Also using the `grafana-cli`  lists it as at version 1.0.1

```
$ grafana-cli plugins ls
installed plugins:
grafana-kairosdb-datasource @ 1.0.1
```

**Comment by jifwin** [comment]
Once we merge #40 it should work fine.

**Comment by rybit** [comment]
Sorry to re-open this but it still seems to not be working. 

I updated the checkout to the latest sha (e01a9c7ebedf931ad536446875d6f9b159689512). then ran the commands:
```
sudo npm install
sudo grunt
```

they both exited fine, but the grunt task had no output (expected?). Then I restarted grafana server.

![image](https://cloud.githubusercontent.com/assets/406376/22750647/78d88288-ede6-11e6-948a-6a6b77e34826.png)


grafana version: `Version 4.1.1 (commit: v4.1.1)`
running on ubuntu 14.04

**Comment by jifwin** [comment]
Strange... It works for me. Is /var/lib/grafana/plugins/kairosdb-datasource/module.js file generated after gruntification?

**Comment by rybit** [comment]
Hmmm no it isn't. Grunt doesn't output anything actually. It has a bad error code and no output. 

```
$ sudo grunt
$ echo $?
1
$ which grunt
/usr/local/bin/grunt
$ npm --version
1.3.10
$ nodejs --version
v0.10.25
```

**Comment by jifwin** [comment]
Are you running it in /var/lib/grafana/plugins/kairosdb-datasource?

**Comment by rybit** [comment]
yup!

**Comment by jifwin** [comment]
Try to install it manually
```
npm install -g grunt-cli
```

And then run again.

**Comment by rybit** [comment]
Ah that is what I had installed on the box. Ran again (with sudo privs). No output when I run grunt from the plugins dir.

**Comment by jifwin** [comment]
Maybe try to update node and npm

root@613f09d5c2d8:/var/lib/grafana/plugins# node --version
v0.12.0
root@613f09d5c2d8:/var/lib/grafana/plugins# npm --version
2.5.1

**Comment by rybit** [comment]
resolved - I think that the issue was that I had nodejs not node installed (installing the legacy package fixed it)
