### ISSUE TITLE
aliasing tags doesn't remove the reference to the tag

### ISSUE THREAD

**Issue by rybit** [grafana/kairosdb-datasource#45]
When I add the appropriate `$_tag_group_reseller` I still see the `(reseller=XXX` in the UI. Is there a way to disable these? 

![image](https://cloud.githubusercontent.com/assets/406376/22799041/2a99743c-eeb9-11e6-87fa-054867a4be4f.png)

**Comment by gauthier-delacroix** [comment]
Same issue here with master @ a561f50395eaee11d3cd369f0af913a18b91c758
