### ISSUE TITLE
Push new release to Grafana.net

### ISSUE THREAD

**Issue by mattttt** [grafana/kairosdb-datasource#46]
Got a report from a very nice user that noticed the version on Grafana.net is approaching a year old but there are more recent versions on Github:

```mattttt: Yeah! kairosdb-datasource-plugin that is served from grafana.net is about a year old. The latest version in GitHub looks ready to go. Wondering why it hasn’t been pushed to Grafana.net yet? We have built build processes around grafana.net api, and it would be great if we could keep using them instead of making a separate build job for Kairos from GitHub. Let me know! :slightly_smiling_face: Thanks in advance```

Told him we'd get a new version released.

**Comment by mattttt** [comment]
```Yeah and there is a nasty bug where if you have “all” selected, it errors out, and CSS is broken, and a few other things in 1.0.1. So we would LOVE to see the new version pushed :slightly_smiling_face:```

**Comment by mattttt** [comment]
When you get back from vacation @daniellee, can you do this quickly? User followed up looking for new version.

**Comment by DanCech** [comment]
2.0.1 is up
