### ISSUE TITLE
Slow autocompletion of tags

### ISSUE THREAD

**Issue by dvenza** [grafana/kairosdb-datasource#47]
We are accumulating data in our cluster for a few months now and will continue to do so for, hopefully, the next few years. We never delete.
The problem is that each time the kairosdb plugin tries to autocomplete a tag it performs a query with start_time set to 0 and kairosdb takes a longer and longer time to respond, hanging the whole interface (cannot save the dashboard, cannot set the tag even when written by hand, etc.).

A possible solution is to restrict the autocomplete query to the time window set for the dashboard: if I set the dashboard for "last three hours" I am probably not interested in the tags of last month.

Also, whenever possible, the plugin should use the [list tag names](https://kairosdb.github.io/docs/build/html/restapi/ListTagNames.html) API instead of the (very costly) [query metric tags](https://kairosdb.github.io/docs/build/html/restapi/QueryMetricTags.html) that returns also the tag values. At least, when I click on on the tag field, it will not try to gather all possible tags and all possible values.

**Comment by jifwin** [comment]
Hi.
I'm facing a similar issue with metric names fetching and suggesting, when the number of them is exceeds reasonable sizes. Basically sorting hundreds of thousands of them causes browser to crash.  
Yes, you are right, this is a big issue. I'm going to work on general refactoring of that plugin, including tag names fetching, but can't give you an ETA. PR welcomed :).

**Comment by alimousazy** [comment]
done, please look at this pull request https://github.com/grafana/kairosdb-datasource/pull/53,  @dvenza and @jifwin
