### ISSUE TITLE
Templated queries issues

### ISSUE THREAD

**Issue by congshenV** [grafana/kairosdb-datasource#49]
1、the KairosDB Plugin Documentation is too old , some web can not open.
2、Whether you can enhance the template request interface , so that I can get tag2 variables  through  tag1 = tag1_value1.
     just like : tag_values(metric,service=$service,host)  
3、Can you make a grafana-kairosdb demo ,   show the KairosDB Plugin function.

**Comment by jifwin** [comment]
1. I'll prepare docs for the next release.
2. Use alternative syntax for templating, instead of $var1_$var2 use [[var1]]]_[[var2]]]
