### ISSUE TITLE
Display bug with Alias legend text.

### ISSUE THREAD

**Issue by Jukkorsis** [grafana/kairosdb-datasource#51]
I think an example would be the best way to show this bug. Let's say I have a query on a metric called "http.duration" with a group by on the tag "status".

If I select default for the Alias, the text that appears beside the select box is "http.duration ( status=$_tag_group_status )". The text that appears in the legend is "http.duration ( status=200 ) ( status=200 ".

if I select "custom" for the Alias, and edit the text to be "$_tag_group_status", then the text in the legend is "200 ( status=200".

if I select "custom" for the Alias, and edit the text to be ".", then the text in the legend is ". ( status=200".

No matter what I enter for the custom Alias, the text "( status=200" gets appended. This even happens when the default Alias is selected.

**Comment by mkeagar** [comment]
We're experiencing this as well with Grafana v4.2.0 and the KairosDB datasource plugin version 2.0.1.

**Comment by jifwin** [comment]
Hi
Thanks for reporting this. Version 3.0.0 is now released. Could you check if the issue still occurs? if so please reopen.
