### ISSUE TITLE
Templating init failed

### ISSUE THREAD

**Issue by julcollas** [grafana/kairosdb-datasource#52]
Hi,

I don't know if this problem is related to the kairosdb plugins, but I have **Templating init failed** error when I load my dashboard, and not all my variables are initialized.

Here are my variables:

- `$host => tag_values(/intel/procfs/cpu/idle_percentage, plugin_running_on)`
- `$interface => tag_values(/intel/procfs/iface/bytes_recv, interface, plugin_running_on=$host)`
- `$cpu => tag_values(/intel/procfs/cpu/idle_percentage, cpuID, plugin_running_on=$host)`
- `$disk => tag_values(/intel/procfs/disk/io_time, disk, plugin_running_on=$host)`

Only $host and $disk are initialized. If I add a new variable $xxx at the end, only $host and $xxx will be initialized.

Do you have any clue ?

Thanks

**Comment by dgfmdrv** [comment]
Hello, I think this is also my problem. When I load my dashboard, shows Templaing init failed [object Object]:
![imagen](https://user-images.githubusercontent.com/1451834/29977671-81f93aa2-8f3e-11e7-89d4-9688275934f7.png)
On chrome console:
![imagen](https://user-images.githubusercontent.com/1451834/29977763-cdd75d46-8f3e-11e7-90f6-9583704b2f81.png)
![imagen](https://user-images.githubusercontent.com/1451834/29977787-e1663990-8f3e-11e7-9717-5ba78acc2e6d.png)

**On firefox** the first variable from datasource  KairosDB gives nothing on combobox:
![imagen](https://user-images.githubusercontent.com/1451834/29977880-3cb47c08-8f3f-11e7-854b-da85bb5307ad.png)

When I click on reload (top-right) shows this error on console and doesn't get reloaded:
![imagen](https://user-images.githubusercontent.com/1451834/29977921-6e0d606c-8f3f-11e7-8579-74bc9dfe0a6e.png)

When I change dashboard's variables, charts doesn't change.

 Tested with:
- KairosDB data source 2.0.1 + Grafana v5.0.0-pre1 (commit: 73f0bd3) 
- KairosDB data source 2.0.1 +  Grafana v4.4.3 (commit: 54c79c5)

**Comment by farzadpanahi** [comment]
Same issue here. Any update?

**Comment by jifwin** [comment]
It will be fixed in the next release.

**Comment by VincentBonnivard** [comment]
Same issue here. When is the next release planned ?

**Comment by jifwin** [comment]
Hi
Thanks for reporting this. Version 3.0.0 is now released. Could you check if the issue still occurs? if so please reopen.
