### ISSUE TITLE
variable can't use in tag query with kairosdb datasource

### ISSUE THREAD

**Issue by fooltux** [grafana/kairosdb-datasource#54]
I define a variable hostname in templates to get a list of my servers. but i can't use it in tag query with kairosdb as my datasource . I 'am user the newest version grafana and the plugin.

**Comment by gauthier-delacroix** [comment]
Same here, tried to repeat a panel based on a tag value but: `No templates variable found`.

**Comment by jifwin** [comment]
Do you mean filtering by tags? It should work now, there were a lot of fixes since may. Otherwise please reopen.
