### ISSUE TITLE
Missing moving average aggregator support

### ISSUE THREAD

**Issue by errnoh** [grafana/kairosdb-datasource#56]
kairosdb-datasource is missing aggregator for moving averages. This is useful feature that is an easy tool to smoothen spiky graphs into more readable form.

Luckily the support for this has been on KairosDB for some months, it's located at https://github.com/kairosdb/kairosdb/blob/master/src/main/java/org/kairosdb/core/aggregator/SmaAggregator.java

Would be nice to have support for this KairosDB feature in Grafana as well.

**Comment by jifwin** [comment]
Hi errnoh
Thanks for pointing that out. I don't see those aggs in kairosdb docs, yet I'm going to add moving average and gaps aggregators to the next release (3.0).
