### ISSUE TITLE
templates get confused when variable name == label

### ISSUE THREAD

**Issue by synfinatic** [grafana/kairosdb-datasource#62]
Tried chaining two variables together in the same template:

name: DC
label: DC
custom_options: DC1,DC2,DC3

name: Hosts
type: Query
query: tag_values(hosts.interface.if_octets.rx_rate, host, dc=$DC)

With the above config, $Hosts returns an empty set.  However, if you change the label from DC to Datacenter, $Hosts returns the hosts in the corresponding DC.

**Comment by jifwin** [comment]
Hi
Thanks for reporting this. Version 3.0.0 is now released. Could you check if the issue still occurs? if so please reopen.
