### ISSUE TITLE
grafana.com version out-of-date

### ISSUE THREAD

**Issue by Spferical** [grafana/kairosdb-datasource#68]
Currently, grafana.com's kairosdb plugin is still on v2.0.1, meaning grafana-cli/etc don't get the latest updates. Is the grafana.com version supposed to be in sync with this repo? It would be convenient to rely on it for new versions.

Thanks!

**Comment by quanganhtran** [comment]
I wonder if it is what they meant in the README by "no longer included out of the box".

**Comment by marefr** [comment]
Please submit a PR here https://github.com/grafana/grafana-plugin-repository to request to publish the latest version of Grafana.com.

**Comment by quanganhtran** [comment]
@marefr we need README.md in `dist`

**Comment by marefr** [comment]
@quanganhtran I just updated the version to 3.0.1 and pushed to master. Please update your PR in https://github.com/grafana/grafana-plugin-repository to reflect the revision of the 3.0.1 version. Thanks!

**Comment by quanganhtran** [comment]
This issue should be resolved by now. The plugin is now available on the Grafana plugin repository.
