### ISSUE TITLE
[Issue] Grafana3 - Kairosdb - query not working - bad url to resource

### ISSUE THREAD

**Issue by vguhesan** [grafana/kairosdb-datasource#7]
Version: Grafana [grafana-3.0.0-pre1.x86_64.rpm] (taken from build on Wed, March 23rd, 2016)
System: CentOS7
Browser: FireFox

When I go to the "query" editor and I choose "KairosDB" as the datasource. The query editor does not render. Upon investigation using FireBug > Network, I can see a 404 on a call to this URL:
http://myserver:3000/public/plugins/kairosdb/partials/query.editor.html?v=1458831580182

Here is a URL for a *similar* html resource that works:
http://myserver:3000/public/app/plugins/datasource/kairosdb-datasource/partials/query.options.html?v=1458831580140

![grafana3_screen1](https://cloud.githubusercontent.com/assets/193960/14021202/e63228bc-f1b0-11e5-8b12-4478df2a65f0.png)

![grafana3_screen2](https://cloud.githubusercontent.com/assets/193960/14021204/e95b13dc-f1b0-11e5-9227-79bec09977f1.png)

Let me know if you need additional information.

Thanks

**Comment by tanpinsiang** [comment]
@vguhesan Check out the 3.0 branch. I also have this problem when using the master branch.

Cheers,
Tan

**Comment by alswl** [comment]
@tanpinsiang thanks, it works for me.

**Comment by torkelo** [comment]
still getting this with latest beta?

**Comment by gmangin** [comment]
yes

**Comment by justmedude** [comment]
I believe that this got resolved with
https://github.com/grafana/kairosdb-datasource/commit/73199379e1c32587d432ebece8df37262790e486
